# Generated by Django 4.2.2 on 2024-12-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='link',
            field=models.URLField(max_length=150),
        ),
    ]
