# Generated by Django 4.2.2 on 2024-12-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_film_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='link',
            field=models.FileField(max_length=150, upload_to=''),
        ),
    ]
