# Generated by Django 4.2.2 on 2024-12-23 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_film_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='thumbnail',
            field=models.FileField(default=django.utils.timezone.now, max_length=150, upload_to=''),
            preserve_default=False,
        ),
    ]
