# Generated by Django 4.2.2 on 2024-12-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='user_id',
            new_name='user',
        ),
    ]
