# Generated by Django 4.2.2 on 2025-01-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_ratings_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='comments',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
