# Generated by Django 4.2.2 on 2025-01-12 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ratings_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.film'),
        ),
    ]
